name: Push Release Tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge_job:
    if: startsWith(github.head_ref, 'develop/') && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: push tag
        env:
          BRANCH_NAME: ${{github.head_ref}}
        run: |
          # develop/1.0.0 → release-1.0.0
          TAG_NAME="${BRANCH_NAME/develop\//release-}" >
          git tag $TAG_NAME
          git push origin $TAG_NAME
